
name: CFML Testing Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    name: Test on ${{ matrix.cfml_engine }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16.x]
        cfml_engine: [lucee@5]
        os: [ubuntu-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        cfml_engine: [lucee@4, lucee@5, adobe@2016, adobe@2018]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

      - name: CFML TestBox Action
        uses: coldfumonkeh/cfml-testbox-action@v1
        with:
          cfml-engine: ${{ matrix.cfml_engine }}
